// Mocks generated by Mockito 5.2.0 from annotations
// in app_sample/test/user_controller_x_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:app_sample/home/domain/model/user_model.dart' as _i4;
import 'package:app_sample/home/domain/user_usecase_list.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [UserUseCaseList].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserUseCaseList extends _i1.Mock implements _i2.UserUseCaseList {
  MockUserUseCaseList() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.User>> getUsers() =>
      (super.noSuchMethod(Invocation.method(#getUsers, []),
              returnValue: Future<List<_i4.User>>.value(<_i4.User>[]))
          as _i3.Future<List<_i4.User>>);
}
